# This is for api telegram bot [0]
- bot: 
  url: 'https://api.telegram.org/bot######'
  token: '######'
  bot_name: '' ### do not have to fill this 
  webserver: 'https://6b18-103-154-125-178.ap.ngrok.io'

- logging:
  logfile: r'path/to/folder'
